// Rotating hints shown centered in the status bar footer when idle.
// Hand-maintained — update alongside shortcuts.ts / feature changes.
export const FOOTER_TIPS: string[] = [
  'Triple-tap ⌘ to bring up the shortcuts overlay',
  'Use ⌘D to split the pane horizontally, or ⌘⇧D to split vertically',
  '⌘P opens the Command Palette',
  '⌘⇧P opens the Action Palette',
  '⌘B toggles the sidebar',
  '⌘K starts an inline edit on the current selection',
  '⌘L sends your selection to Claude, or opens chat',
  '⌘F finds in the current file, ⌘⇧F finds across the whole project',
  '⌘T opens a new terminal tab',
  '⇧⇥ toggles Bridge agent mode',
  '⌘⇧T reopens the last closed tab',
  '⌘, opens Preferences',
  'Right-click a file in the sidebar for more options',
  'Right-click an image to view it as raw code instead',
  'Right-click a markdown file to open it in the Markdown Viewer',
  'Gitignored files show dimmed in the sidebar tree',
  'The sidebar stays in sync with changes made outside vIDE, like in Finder or a terminal',
  '⌘⇧N opens a new window on a different project',
  '⌘O opens a project folder',
  '⌃R opens the Switch Project palette — hold ⌘ (or Ctrl on Linux) at Enter to open it in a new window',
  '⌃R jumps to an already-open project\'s window instead of reopening it',
  '⌘-click a symbol to jump to its definition — enable a language under Settings > Editor > Language Intelligence',
  'The Graphify panel turns your codebase into a queryable knowledge graph — ask it questions instead of grepping',
  'Pair your phone from the Mobile Display panel — scan the QR code and enter the PIN',
  'Enable To Do in Settings to pin a task-tracking page as a browser tab in the sidebar',
  'Open an in-app browser tab from the activity bar to preview your app next to the code',
  'The Usage button on the Claude panel shows live token usage and cost',
]
